### ISSUE TITLE
elasticsearch CORS configuration

### ISSUE THREAD

**Issue by mmai** [mmai/elastic_librarything#4]
edit `config/elasticsearch.yml` on docker image : 

```yml
network.host: 0.0.0.0
http.cors.enabled : true
http.cors.allow-origin: "*"
http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : "X-Requested-With,X-Auth-Token,Content-Type, Content-Length, uthorization"
```
